np_seed: 6
torch_seed: 6
fold_seed: 98
batch_size: 8
total_epochs: 500
dataset_dir: '/data/ninad/fieldmaps/'
result_dir: '/home/neelamlab/ninad/DWI/results'
mae_dir: '/home/neelamlab/ninad/DWI'
label_dir: '/data/ninad/fieldmaps/HCPCN2mm.csv'
age_threshold: 0
task: 'classification'
model: 'SFCN2'
dropoutrate: 0.5
early_stopping_patience: 15
kfolds: 5
save_every: 25
lr: 0.0001
weight_decay: 0.001
optimizer: 'Adam'
loss: 'BCEWithLogitsLoss'
test_ratio: 0.2
stratify: True
note: 'Training with all the 4 channels as input: in the order: '